include:
- ./func/*
kind: ArchiveUploadSpec
name: func-Ud0d

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: suita-profile-update-fn-162f61d6-6334-4396-9f87-d1915cb160e9
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: suita-profile-update-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-Ud0d
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-10-19T21:27:02Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: suita-profile-update-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: suita-profile-update-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.update_suitability_profile
    packageref:
      name: suita-profile-update-fn-162f61d6-6334-4396-9f87-d1915cb160e9
      namespace: default
  requestsPerPod: 10000
  resources: {}
