apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: acc-suit-quest-update-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: acc-suit-quest-update-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /suitability/profile_update
    tls: ""
  method: ""
  methods:
  - PUT
  prefix: ""
  relativeurl: /suitability/profile_update
